### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by qingxuluo** [wujunyang/jiaModuleDemo#1]
你好,可以给个联系方式吗?有点问题想问一下

**Comment by wujunyang** [comment]
你好，是有碰到什么问题么？

**Comment by qingxuluo** [comment]
两个问题
1，想问一下我podspec里面依赖的友盟的分享sdk不支持i386架构，导致一直校验不通过怎么解决。。
2，你依赖的UMAnalytics应该也是framework或者是library形式吧，不需要添加vendored_framework或者vendored_library么。只需要--use libraries就可以啦么？

发自网易邮箱大师
在2016年09月29日 20:11，tabwu 写道:

你好，是有碰到什么问题么？

**Comment by wujunyang** [comment]
--use libraries  用在依赖有第三方静态库SDK时，好比如项目中的个推SDK、友盟统计SDK;你不应该直接把SDK下载引入到项目中，而是让它依赖自个去下载引用；

**Comment by qingxuluo** [comment]
是的，是这样用的，本身就是为了解决不再需要手动导入，只是目前这种情况下碰到了友盟分享不支持i386架构的问题，导致push不到私有仓库，想问问你怎么解决。。

发自网易邮箱大师
在2016年09月29日 22:02，tabwu 写道:

--use libraries 用在依赖有第三方静态库SDK时，好比如项目中的个推SDK、友盟统计SDK;你不应该直接把SDK下载引入到项目中，而是让它依赖自个去下载引用；

**Comment by wujunyang** [comment]
友盟我倒没有试过  但个推我先前是有把它的SDK下载包含在我的文件中，你可以查看一下：https://github.com/wujunyang/jiaGTSDK  我有测试过没有问题，对了 对于你把SDK拿下来就要自个来管理这个SDK的版本问题，也是比较麻烦；

**Comment by qingxuluo** [comment]
嗯。下载下来再做成pods也有想过，只是还是想能不能直接以依赖的形式引进来，毕竟如果能解决就少了一个库的维护成本。谢谢你，我再找找方法😂

发自网易邮箱大师
在2016年09月29日 22:16，tabwu 写道:

友盟我倒没有试过 但个推我先前是有把它的SDK下载包含在我的文件中，你可以查看一下：https://github.com/wujunyang/jiaGTSDK 我有测试过没有问题，对了 对于你把SDK拿下来就要自个来管理这个SDK的版本问题，也是比较麻烦；

**Comment by wujunyang** [comment]
友盟分享不支持i386  这个友盟本来就不支持的  应该不是跟你这个封装有关的

**Comment by qingxuluo** [comment]
是的，我想解决的是我既依赖他这个库，又可以成功push repo。。然而现在看来这种方式是不可行的，我在cocoapods的issues找到了同样的问题，然后官方成员认为不可行。。

发自网易邮箱大师
在2016年09月30日 14:23，tabwu 写道:

友盟分享不支持i386 这个友盟本来就不支持的 应该不是跟你这个封装有关的
