### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by ErHu1993** [wujunyang/jiaModuleDemo#10]
/Users/xxx/Downloads/jiaModuleDemo-master/Pods/AFNetworking/UIKit+AFNetworking/UIButton+AFNetworking.m:29:9: 'AFImageDownloader.h' file not found

**Comment by wujunyang** [comment]
你好 可以尝试进行更新pod

**Comment by tengshuq** [comment]
更新了还是报错1.3.1

**Comment by tengshuq** [comment]
@wujunyang 更新了还是报错1.3.1

**Comment by JohnChaseK** [comment]
报错了，还是说缺少#import "AFImageDownloader.h"  这个头文件

**Comment by wujunyang** [comment]
@zhouzhuhao  你本地用的AF是什么版本？目前本项目用的是'AFNetworking', '~> 3.0'

**Comment by EarthMass** [comment]
'AFNetworking', '~> 3.0' pod下来还是 3.1.0
修改成'AFNetworking', '~> 3.0.4' 
又开始报 #import "GeTuiSdk.h"这个文件找不到
#import <GTSDK/GeTuiSdk.h> 这样引入就没问题了

**Comment by Aaron-Fan** [comment]
pod update 之后还是AFImageDownloader.h' file not found ？
 
作者能更新下吗？

**Comment by wujunyang** [comment]
@EarthMass   因为项目中目前引入的个推SDK这段时间已经更新好几个版本 所以有差异；大家可能看的是实现方式；毕竟第三方插件更新时我这边对于代码可能不能及时修改

**Comment by wujunyang** [comment]
@Aaron-Fan  这个可能是AF版本的版本差异导致

**Comment by wujunyang** [comment]
我刚把pod对应的插件更新了  本地没有问题  你们可以尝试一下；感谢关注

**Comment by ice19910402** [comment]
我这边还是有问题...

**Comment by ice19910402** [comment]
@wujunyang
