### ISSUE TITLE
项目运行错误

### ISSUE THREAD

**Issue by myworldhere** [wujunyang/jiaModuleDemo#11]
首先，pod完后运行，AFImageDownloader.h 文件找不到，发现是因为目前pod install 会更新AFN3.1.0版本，这个版本应该是没有AFImageDownloader这个类了。所有我把pod 'AFNetworking', '~>3.0' 改成了'AFNetworking', '3.0'指定更新3.0版本。不再提示找不到AFImageDownloader.h文件了。但是又出现了新的问题，RealReachability库里的 PingFoundation.h 类中
check_compile_time(sizeof(ICMPHeader) == 8);
check_compile_time(offsetof(ICMPHeader, type) == 0);
check_compile_time(offsetof(ICMPHeader, code) == 1);
check_compile_time(offsetof(ICMPHeader, checksum) == 2);
check_compile_time(offsetof(ICMPHeader, identifier) == 4);
check_compile_time(offsetof(ICMPHeader, sequenceNumber) == 6);
这几个调用 提示 提示 Expected parameter declarator， 问题指向这里offsetof

**Comment by wujunyang** [comment]
我刚把pod对应的插件更新了  本地没有问题  你们可以尝试一下；感谢关注
