### ISSUE TITLE
demo一打开就报错啊

### ISSUE THREAD

**Issue by summer87279149** [wujunyang/jiaModuleDemo#2]
clang: error: no such file or directory: '/Users/admin/Desktop/jiaModuleDemo-master/Pods/Target Support Files/CocoaLumberjack/CocoaLumberjack-dummy.m'
clang: error: no input files

**Comment by wujunyang** [comment]
你好 感谢关注  这个问题你只要更新一下POD就可以了

**Comment by bluesea** [comment]
pod 更新不到你的部分文件，比如umeng那块
