### ISSUE TITLE
网络状态监控

### ISSUE THREAD

**Issue by bluesea** [wujunyang/jiaModuleDemo#3]
AF其实也有这功能，没必要再使用一个第三方

**Comment by wujunyang** [comment]
您好 因为AF感觉不好用 所以才引入另外一个插件

**Comment by bluesea** [comment]
感觉用法差不多- -。
你里面用的YTKNetWorking的框架也已经支持AF3.0了~~

**Comment by wujunyang** [comment]
恩  先前有看他们最近才开始转到AF3.0  等过段时间比较稳定后  再进行调整; 对于项目用到的那个网络判断库你可以到它的GIT查看，有介绍相应的不同点；
