### ISSUE TITLE
download`demo can`t running!

### ISSUE THREAD

**Issue by CavanLife** [wujunyang/jiaModuleDemo#4]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GeTuiSdk", referenced from:
      objc-class-ref in XAspect-GeTuiAppDelegate.o

**Comment by wujunyang** [comment]
感谢关注
你可以尝试清空工程，然后进行POD更新

**Comment by Hoolink** [comment]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GeTuiSdk", referenced from:
      objc-class-ref in XAspect-GeTuiAppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

pod 完毕还是有这个问题。请问怎么解决。。

**Comment by BainJ** [comment]
可以把项目中的 pod 文件夹和 podfile.lock文件全部删掉然后在更新 pod

**Comment by CavanLife** [comment]
@hulinhu521 ， 删掉 Podfile 中的 GeTuiSdk，然后更换成pod 'GTSDK', '~> 1.5.3'这个，重新执行 pod install。我记得当时我是这样解决的。希望能有所帮助。

**Comment by yoowei** [comment]
将podfile里面的对应的第三方描述，先注销，然后pod install。完事之后，打开注销，再次pod install就OK了。
