### ISSUE TITLE
JiaCore没有像demo那样，根据功能分组到对应的文件夹

### ISSUE THREAD

**Issue by OldBulls** [wujunyang/jiaModuleDemo#7]
是不是文件夹没有在工程文件夹里新建，直接建的虚拟文件夹

**Comment by wujunyang** [comment]
你好，有建，不知道哪有问题？

**Comment by OldBulls** [comment]
在pods文件夹里是有分组，但是打开工程后，再看里面没分组![Uploading 屏幕快照 2017-01-10 上午9.15.36.png…]()

**Comment by OldBulls** [comment]
<img width="685" alt="2017-01-10 9 34 53" src="https://cloud.githubusercontent.com/assets/9461547/21790548/21ba0b14-d718-11e6-9b95-1a8754f68cd5.png">

**Comment by wujunyang** [comment]
恩 你意思是引入POD时 新项目中就没有目录？这个是私有POD不会把目录带过去，这个找个时间我研究一下；

**Comment by OldBulls** [comment]
恩呢，打开项目后，目录是这样的
<img width="384" alt="2017-01-10 9 53 41" src="https://cloud.githubusercontent.com/assets/9461547/21790999/dd64ee22-d71a-11e6-8720-c774796ff4df.png">

**Comment by OldBulls** [comment]
目录分级问题，我解决了，参考官方的示例：https://guides.cocoapods.org/making/specs-and-specs-repo.html
在A specification with subspecs章节 有一个示例

在podspecs中代码
`znCore.source_files = 'ZNCoreModule/Classes/ZNCore/*.{h,m}','ZNCoreModule/Classes/ZNCore/{ZNCoreHelper,ZNCoreTool,ZNMediator}/**/*.{h,m}'`
但是我在更新本地私有库的时候，提交到后出现了一个错误，不知道怎么回事
<img width="568" alt="2017-01-12 6 18 34" src="https://cloud.githubusercontent.com/assets/9461547/21885761/14e73c4e-d8f4-11e6-8524-27419526394a.png">
